#!/bin/bash

prefix="./some/path/"

for dir in ${prefix}zeroed*/; do
    if [ -d "$dir" ]; then
        # Redirecting output to a file named "output.txt", appending to its contents
        python3 your_script.py "$dir" >> output.txt
    fi
done
